# Generated by Django 2.2.7 on 2019-12-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('mgts', models.TextField(blank=True, null=True)),
                ('ats_ogv', models.TextField(blank=True, null=True)),
                ('mestniy', models.TextField(blank=True, null=True)),
                ('room', models.TextField(blank=True, null=True)),
                ('gate', models.TextField(blank=True, null=True)),
                ('otdel', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
