# Generated by Django 2.2.7 on 2019-12-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telspr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='person',
            name='ats_ogv',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='АТС-ОГВ'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mestniy',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Мест'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mgts',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='МГТС'),
        ),
        migrations.AlterField(
            model_name='person',
            name='otdel',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='person',
            name='room',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='person',
            name='second_name',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
